package Client;


import Protocol.CommunicationProtocol;
import Protocol.Client;
import java.io.File;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class ConnectToServerDialogGUI extends javax.swing.JDialog {
    MainGUI parentMain;
    String pathToSharedDirectory;
    File[] files;

    /**
     * Creates new form ConnectToServerDialog
     */
    public ConnectToServerDialogGUI(MainGUI parent, boolean modal) {
        super(parent, modal);
        parentMain = (MainGUI) parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        serverIpTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        serverPortTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        javax.swing.JButton connectToServerButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        sharedFolderTextField = new javax.swing.JTextField();
        chooseFolderButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        filesPortTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        networkPortTextField = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("IPv4 of the Server");

        jLabel2.setText("Server Port");

        jLabel3.setText("Name");

        connectToServerButton.setText("Connect to Server");
        connectToServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectToServerButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Folder to Share");

        chooseFolderButton.setText("Choose Folder");
        chooseFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFolderButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Port for Receiving Files");

        jLabel6.setText("Port for Network Communications");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(connectToServerButton)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serverIpTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addComponent(serverPortTextField)
                    .addComponent(nameTextField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sharedFolderTextField)
                        .addGap(18, 18, 18)
                        .addComponent(chooseFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filesPortTextField)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(networkPortTextField))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(serverIpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(serverPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(filesPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(networkPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sharedFolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseFolderButton))
                .addGap(32, 32, 32)
                .addComponent(connectToServerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectToServerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectToServerButtonActionPerformed
        //Get data
        String ipServer = serverIpTextField.getText();
        String portServer = serverPortTextField.getText();
        String portFiles = filesPortTextField.getText();
        String portNetwork = networkPortTextField.getText();
        String nomeCliente = nameTextField.getText();
        
        //Validate data
        InetAddress ipServerInet = null;
        int portServerInt = -1;
        int portFilesInt = -1;
        int portNetworkInt = -1;
        try{
            ipServerInet = InetAddress.getByName(ipServer);
        }
        catch(UnknownHostException e){
            JOptionPane.showMessageDialog(null, "Invalid IP entered", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
            portServerInt = Integer.parseInt(portServer);
            portFilesInt = Integer.parseInt(portFiles);
            portNetworkInt = Integer.parseInt(portNetwork);
            
            if(portServerInt < 1023 || portServerInt > 65535){
                JOptionPane.showMessageDialog(null, "Server port is out of the valid range. Please enter a port between 1024 and 65535","ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(portFilesInt < 1023 || portFilesInt > 65535){
                JOptionPane.showMessageDialog(null, "File port is out of the valid range. Please enter a port between 1024 and 65535", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(portNetworkInt < 1023 || portNetworkInt > 65535){
                JOptionPane.showMessageDialog(null, "Network port is out of the valid range. Please enter a port between 1024 and 65535", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Invalid port entered", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Get all files (including those in subdirectories) from a directory
        File sharedDirectory = new File(pathToSharedDirectory);
        if(sharedDirectory.exists() && sharedDirectory.isDirectory()){
            try {
                // walk generates a stream. A stream is a way to manipulate collections of data functionally,
                // without the need for traditional loops. Therefore, map and toArray
                // are Stream methods and are applied to each element of the stream.

                // walk traverses the entire directory, obtaining directories, subdirectories, and all their files
                // filter filters the elements so that only files remain, not directories
                // map converts these paths to File objects
                // toArray converts the stream into a File[]
                files = Files.walk(Paths.get(pathToSharedDirectory))
                        .filter(path -> Files.isRegularFile(path))
                        .map(path -> path.toFile())
                        .toArray(size -> new File[size]);
            } catch (IOException ex) {
                Logger.getLogger(ConnectToServerDialogGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "The directory does not exist", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        //Send data
        try{
            Socket socketServer = new Socket(ipServerInet.getHostAddress(), portServerInt);
            ObjectOutputStream objectOutput = new ObjectOutputStream(socketServer.getOutputStream());
            ObjectInputStream objectInput = new ObjectInputStream(socketServer.getInputStream());
            
            Client clientForLoggin = new Client(nomeCliente, InetAddress.getLocalHost().getHostAddress(), portNetworkInt, files);
            CommunicationProtocol request = new CommunicationProtocol("LOGIN");
            request.setClientForLogin(clientForLoggin);
            objectOutput.writeObject(request);
            objectOutput.flush();
            
            CommunicationProtocol response = (CommunicationProtocol) objectInput.readObject();
            
            //Close resources
            objectOutput.close();
            objectInput.close();
            socketServer.close();
            
            if(response.getCodeProtocol().equalsIgnoreCase("OK")){
                JOptionPane.showMessageDialog(null, response.getMessage(),  "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                parentMain.recebirDadosLoginFromDialog(nomeCliente, portServerInt, portFilesInt, portNetworkInt, ipServerInet, response.getMulticastGroup(), response.getMulticastGroupPort(), pathToSharedDirectory, response.getActiveClients(), files);
            }
            else{
                JOptionPane.showMessageDialog(null, response.getMessage(),  "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        catch(IOException | ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, "An error occurred while trying to connect to the server", "ERROR!", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_connectToServerButtonActionPerformed

    private void chooseFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFolderButtonActionPerformed
        FileChooserDialogGUI fileChooserDialog = new FileChooserDialogGUI(ConnectToServerDialogGUI.this, true);
        fileChooserDialog.setVisible(true);
    }//GEN-LAST:event_chooseFolderButtonActionPerformed

    public void recebirDiretorioFromDialog(String path){
        pathToSharedDirectory = path;
        sharedFolderTextField.setText(path);
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseFolderButton;
    private javax.swing.JTextField filesPortTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField networkPortTextField;
    private javax.swing.JTextField serverIpTextField;
    private javax.swing.JTextField serverPortTextField;
    private javax.swing.JTextField sharedFolderTextField;
    // End of variables declaration//GEN-END:variables
}
